<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhKWWrU\EccubeEccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhKWWrU/EccubeEccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXhKWWrU.legacy');

    return;
}

if (!\class_exists(EccubeEccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXhKWWrU\EccubeEccube_KernelProdContainer::class, EccubeEccube_KernelProdContainer::class, false);
}

return new \ContainerXhKWWrU\EccubeEccube_KernelProdContainer([
    'container.build_hash' => 'XhKWWrU',
    'container.build_id' => '66ae5e7e',
    'container.build_time' => 1650643051,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhKWWrU');
