<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Coupon4\Form\Type\CouponUseType' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/app/Plugin/Coupon4/Form/Type/CouponUseType.php';

return $this->privates['Plugin\\Coupon4\\Form\\Type\\CouponUseType'] = new \Plugin\Coupon4\Form\Type\CouponUseType();
